# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: TerraformInstaller@1
  inputs:
    terraformVersion: 'latest'
  displayName: 'Install Terraform'
- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'init'
    backendServiceAWS: '(Cloudfront_Terraform)AWS_for_terrafrom'
    backendAWSBucketName: 'ohbster-ado-terraform-class5'
    backendAWSKey: 'cloudfront/frontend/terraform.tfstate'
  displayName: 'Initialize Terraform'

- task: TerraformTaskV4@4
  inputs:
    provider: 'aws'
    command: 'apply'
    commandOptions: '--auto-approve'
    environmentServiceNameAWS: '(Cloudfront_Terraform)AWS_for_terrafrom'
  displayName: 'Apply Terraform'

- task: AWSCLI@1
  inputs:
    awsCredentials: '(Cloudfront_Terraform)AWS'
    regionName: 'us-east-1'
    awsCommand: 'cloudfront'
    awsSubCommand: 'create-invalidation'
    awsArguments: '--distribution-id "E3MU3PWGRMQQIP" --paths "/*"'